# utils/file_utils.py

import os
import re
from pathlib import Path

def ensure_directory_exists(directory_path: Path):
    """Ensure the given directory exists; create it if necessary."""
    try:
        directory_path.mkdir(parents=True, exist_ok=True)
    except Exception as e:
        print(f"An error occurred while creating directory '{directory_path}': {e}")

def construct_folder_path(base_path: Path, *sub_paths) -> Path | None:
    """
    Construct a folder path by joining base_path with sub_paths.
    Ensures the folder exists.
    Returns the Path object or None if error.
    """
    try:
        folder_path = base_path.joinpath(*sub_paths)
        ensure_directory_exists(folder_path)
        return folder_path
    except Exception as e:
        print(f"An error occurred while constructing folder path: {e}")
        return None

def sanitize_filename(filename: str) -> str:
    """
    Sanitize filename by replacing invalid characters with underscores.
    Invalid chars include: <>:"/\|?* and control chars.
    """
    return re.sub(r'[<>:"/\\|?*\x00-\x1F]', '_', filename)

# Detect user's Desktop folder cross-platform
def get_desktop_folder() -> Path:
    """
    Returns the Path to the user's Desktop directory.
    Works on Windows, macOS, Linux.
    """
    if os.name == 'nt':  # Windows
        return Path(os.getenv('USERPROFILE', '')) / 'Desktop'
    else:
        # macOS/Linux
        return Path.home() / 'Desktop'

# --------------------------
# Exemplo de uso
if __name__ == '__main__':
    desktop_folder = get_desktop_folder()
    print(f"Desktop folder detected as: {desktop_folder}")

    # Construir caminho de pasta
    my_folder = construct_folder_path(desktop_folder, "MyProject", "Output")
    if my_folder:
        print(f"Folder created at: {my_folder}")

    # Gerar nome de arquivo sanitizado
    bad_name = 'relatório: junho/2025?.md'
    safe_name = sanitize_filename(bad_name)
    print(f"Sanitized filename: {safe_name}")

    # Exemplo de salvar arquivo vazio
    file_path = my_folder / safe_name
    file_path.write_text("# Example Markdown\n\nGenerated by script.\n", encoding='utf-8')
    print(f"File created at: {file_path}")
